services:
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_DB=mydb  
    volumes:
      - ./init-influxdb.sh:/docker-entrypoint-initdb.d/init-influxdb.sh  # Run script at startup

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - /tmp/influxdb-config.env:/etc/grafana/.env  # Mount the InfluxDB configuration file
    depends_on:
      - influxdb

  k6:
    image: grafana/k6:latest
    container_name: k6
    entrypoint: [ "k6" ]
    command: [ "run", "--out", "influxdb=http://influxdb:8086/mydb", "/scripts/my-test-script.js" ] 
                                                  # Alterar o nome dos scripts conforme necessário
    volumes:
      - ./scripts:/scripts # Maps the K6 scripts directory
    depends_on:
      - influxdb