version: '3.3'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_DB: k6_results
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  xk6:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xk6
    depends_on:
      - postgres
    volumes:
      - ./scripts:/scripts
    entrypoint: ["k6", "run", "/scripts/script.js"]

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/postgres
  grafana-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/grafana

