version: '3.8'
services:

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=my-bucket
    volumes:
      - ./create-token.sh:/docker-entrypoint-initdb.d/create-token.sh  # Run script at startup

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - /tmp/influx_token.env:/etc/grafana/.env  # Mount the token file
    depends_on:
      - influxdb


  k6:
    image: grafana/k6:latest
    container_name: k6
    entrypoint: [ "k6" ]
    command: [ "run", "--out", "influxdb=http://influxdb:8086", "/scripts/my-test-script.js" ]
    volumes:
      - ./scripts:/scripts # Maps the K6 scripts directory
    depends_on:
      - influxdb
