apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    database: ${INFLUXDB_DB}  # Use the database name defined in your InfluxDB
    user: ${INFLUXDB_ADMIN_USER}  # Username for InfluxDB (as defined in the environment variables)
    password: ${INFLUXDB_ADMIN_PASSWORD}  # Password for the InfluxDB user
    jsonData:
      version: InfluxQL  # InfluxDB 1.x uses InfluxQL by default (instead of Flux)

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      
  - name: Promtail
    type: promtail
    access: proxy
    url: http://promtail:9080
    jsonData:
      maxLines: 1000