apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    database: my-bucket
    user: admin
    secureJsonData:
      token: ${INFLUX_TOKEN}
    jsonData:
      organization: my-org
      defaultBucket: my-bucket
      version: Flux
